version: "3.8"

services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/fabio-dev/kube_news/postgre_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net


volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge